### ISSUE TITLE
How-To for ResBundle usage with external files

### ISSUE THREAD

**Issue by semanticfire** [iLib-js/ilib-webpack-loader#12]
Hi,

I'm exactly at this point with ilib integration
https://sourceforge.net/p/i18nlib/discussion/localization/thread/2843fad0/

I've used ilib in the past with enyo and used the exact structure as above, however with webpack I'm totally in the blue how to solve this.

A howto for resource bundles in separate files would be great!

Bart

**Comment by ehoogerbeets** [comment]
Hi Bart,

Since that sourceforge discussion 5 years ago, I've written and open-sourced a localization tool that should be able to help. Take a look at https://github.com/iLib-js/loctool 

It should be able to extract strings from js and put them into xliff files that you can send to your translators. From there, when you get the translated xliffs back, you can run the loctool again, and this time, it will generate the translated .js files for you. From there, you will need to require those .js files somewhere in your code so that webpack will automatically bundle them. Doing it with require will bundle all of the translations for all the locales together. If you have a lot of translations and the files are big, you will want to load the files dynamically instead of including them all into your webpack bundle. You can do this by wrapping your whole code in an async call to System.import() to dynamically load the .js files for the locale. Webpack will produce chunks for those files which can be loaded dynamically. Something like:

```
function loadTranslations(locale, callback) {
  switch (locale) {
    case 'en-US':
      System.import("./en-US.js", function() {
        callback();
      });
      break;
    case 'nl-NL':
      System.import("./nl-NL.js", function() {
        callback();
      });
      break;
     ... one case for every locale your app needs to support
  }
}
```

The reason you use a big switch statement instead of calculating the file name something like `System.import('./' + locale + '.js', function() {})` is that when you construct the name of the file, webpack will have a hard time figuring out which files to bundle exactly. It ends up bundling ./*.js which is probably not what you want. The switch statement is more cumbersome, but webpack will grab only the files you actually need.

If you are using webpack with react (or soon, enact), you can preview the not-yet-ready-for-prime-time project react-ilib at https://github.com/iLib-js/react-ilib  It will have the ability to dynamically load translations like that in a react idiomatic way, and it will provide translation components that will depend on ilib's ResBundle to do translations. The translation component will look something like:

```
<Translate id="unique.id.here" description="translator comment" values={{awesome: "awesome"}}>
   Text to translate with <b>embedded HTML</b> and <Param name="awesome"/> replacement params.
</Translate>
```

The loctool will be enhanced to pull out those strings and get them translated, and then write out .js files with the translations that the react-ilib components will be able to load dynamically.

Let me know if I answered the question, or if you have any follow-up questions. I'll be writing a deeper description in the loctool's documentation.

**Comment by ehoogerbeets** [comment]
Yes, that makes it easy. Just convert the json files to a js file like this:

```
var ilib = require("ilib");
ilib.data.strings = { your english json here if you have one };
ilib.data.strings_nl = { your dutch json here };
ilib.data.strings_de = { your german json here };
etc.
```
And then require that file, and ilib should be able to find the strings when you do `var rb = new ResBundle();`

**Comment by semanticfire** [comment]
if I require ilib with webpack I get a webpack error:
```
ERROR in ./node_modules/ilib/lib/NodeLoader.js
Module not found: Error: Can't resolve 'fs' in '/home/bart/jsgit/litelement-pack/node_modules/ilib/lib'
```

**Comment by ehoogerbeets** [comment]
Yes, you have to use the "experimental" version of ilib. (ie. > 14.0). It's pretty close to becoming the "latest" version, but not quite yet.

`npm install ilib@experimental`

Then, you need to include the ilib-webpack-loader and ilib-webpack-plugin into your webpack.config.js as per the docs in the ilib-webpack-loader project.

**Comment by semanticfire** [comment]
After installing the experimental I ended up with this solution:

```
var ilib = require('ilib')

ilib.data.strings_en = require('resources/en/strings.json')
ilib.data.strings_nl = require('resources/nl/strings.json')
ilib.data.strings_de = require('resources/de/strings.json')
```

The resource bundle now correctly uses these settings.

With the appropriate plugins and settings in webpack this mimics the original behavior I had.
