### ISSUE TITLE
Error building on Windows due to absolute/unescaped paths

### ISSUE THREAD

**Issue by chrilyng** [iLib-js/ilib-webpack-loader#16]
First of all thanks for this awesome project.

This is a minor issue but I've run into trouble building a custom locale ilib library on Windows due to (as far as I can figure out) the generated dependency paths in outputPath having unescaped absolute file paths.
This gives Node/Webpack invalid paths in the resulting JS e.g.
`var en_GB = require('C:\project-path\assets\en_GB.js`

I fixed it by replacing backslash with a double backslash in outputPath (just before line 149) but since I'm kind of new to Webpack and Node I'm not sure if there is a better way for cross-platform compatibility? I think forward slash could work cross platform if the path was relative?

Also the documentation is pretty good but the only example I could see of referencing the library is by nesting it in HTML UMD-style. However we're using it in another Webpack project and ended up using `libraryTarget: 'window'` to get it to work. That's probably more specific to knowing how to configure Webpack than ilib but just thought I'd mention it.

**Comment by ehoogerbeets** [comment]
Hi @chrilyng thanks for taking the time to give this feedback! I looked at the code, and you had the right idea. The problem here is that the loader is producing JS code at that point, so in order to escape it properly from the js interpreter twice (once in the loader, and once when the code that the loader produces is interpreted), it has to have backslashes doubled. I'm going to make a PR for that shortly.

**Comment by ehoogerbeets** [comment]
Hello @chrilyng, please take a look at the code in the branch for the above PR. This code does not break Linux or Mac, but I don't know if it will fix Windows. Can you try it for me and let me know? Thank you!

**Comment by ehoogerbeets** [comment]
Oh, and as for using ilib as a UMD-style library... I would just use ilib directly in your original webpack code instead of using it as a library. Then, add the ilib-webpack-loader and ilib-webpack-plugin to your original webpack.config.js file. Then, if you are using webpack 4, you can use optimization.splitChunks to split ilib chunks automatically from your main program so that you don't end up with giant chunks.

**Comment by ehoogerbeets** [comment]
Version v1.3.1 published on npm. Let me know if that works or doesn't work for you!

**Comment by chrilyng** [comment]
Works like a charm, thanks!

Sorry I didn't reply earlier but thanks again for the quick fix.

Regarding webpack: I tried including ilib loader directly in the array of configs both before or after our main webpack config but I think I messed something up (probably might be webpackMerge messing with things) because it had trouble finding ilib in the import/require for the main build. 
It probably doesn't make things easier that we're also using typescript and right now I'm just really happy it works :)

**Comment by ehoogerbeets** [comment]
Hi @chrilyng, thanks for checking that. If you are using typescript, you maybe want to check out the iLib-js/ilib-es6 project. It has promise-based es6 wrappers for all of the ilib classes, so you can simply import the classes instead of using `require`. You can still use ilib-webpack-loader the same way as before.
